### ISSUE TITLE
Only admin can login with other user credentials?

### ISSUE THREAD

**Issue by Allan-Nava** [mpyrev/django-host-user-override#1]
Hi,

I need a feature like Netflix users management, that one users can impersonate the "children"

Thanks for support!

**Comment by mpyrev** [comment]
Sorry, I don't use Netflix and don't know about what you're talking about exactly.
If you need simple «login as different user» feature than go with [django-loginas](https://github.com/skorokithakis/django-loginas). django-host-user-override is more complicated in setup and for users who need to be logged in as different users in different tabs _at the same time_.

**Comment by Allan-Nava** [comment]
Hi @mpyrev ,

Is possibile to manage the users inside the main user?

Such as the netflix feature where there is a only 1 one account that can handle and manage the 4 "childrens"

**Comment by mpyrev** [comment]
I see what you mean. I'm affraid you should write custom solution for your problem. You want User instance to have up to 5 profiles (4+1 for the user himself) and to switch between them on the fly.
Create model for profiles with fk to User. Keep info about current profile in session (```request.session```), allow user to select which one he wants active and update session.

**Comment by Allan-Nava** [comment]
Ok,

I have this class **Profile**

```
@python_2_unicode_compatible
class Profile(models.Model):
     user        = models.OneToOneField(User)
    location    = models.CharField(max_length=50, null=True, blank=True)
    url         = models.CharField(max_length=50, null=True, blank=True)
    job_title   = models.CharField(max_length=50, null=True, blank=True)
```

I added this line:
`parent              = models.ForeignKey('Profile', null=True, blank=True)`

I think is not correct, what do you think?

**Comment by mpyrev** [comment]
User model is your «account» and Profile is your, well, «profile». Replace OneToOneField with ForeignKey, so you can have multiple profiles for one user. ```parent``` line is unnecessary.

For additional help please ask on StackOverflow. This issue becomes offtopic. :)
